# -*- coding: utf-8 -*-
"""Ai/ML_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGgLyO6u4yNXx2hFRzYXjCoGf3TYZ1iC
"""

# Import libraries

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# Read Csv File

df = pd.read_csv("/content/Cleaned_Dataset.csv")
print(df)

# Data Explore

df.info()
df.describe(include="all")

# Check Null values if exists

print(df.isnull().sum())

# Histogram

df.hist(figsize=(10,8), bins=20)
plt.show()

# Box Plot

sns.boxplot(x="Pclass", y="Age", data=df)
plt.show()

# pairplot

sns.pairplot(df[['Survived','Age','Fare','Pclass']], hue='Survived')
plt.show()

# interactive plot (plotly)

fig = px.scatter(df, x='Age', y='Fare', color='Survived', size='Pclass')
fig.show()

# Anomaly Detect by groupBy

df.groupby('Sex')['Survived'].mean()
df.groupby('Pclass')['Survived'].mean()



# Visualize

sns.barplot(x='Pclass', y='Survived', hue='Sex', data=df)
sns.histplot(df['Age'], kde=True)