# -*- coding: utf-8 -*-
"""AI/ML_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvdfTn8xWNNZqffNSjYfNG26JFxtA_s6
"""

# Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

# Load the Data

df = pd.read_csv("/content/Titanic-Dataset.csv")
print(df)

# Information of data and its data types

print(df.info())

# Top 5 Data
print(df.head())

# Describe the data

print(df.describe())

# Check Null Values in data with thier sum

print(df.isnull().sum())

# Handling Missing Values and drop null values columns

# Fill Age with median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Fill Embarked with mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Drop Cabin (too many nulls)
df.drop(columns=['Cabin'], inplace=True)

# Label Encoding and one hot coding

# Label encode 'Sex'

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])  # male=1, female=0

# One-hot encode 'Embarked'
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Normalize between (0 - 1) and Standardization mean(0) and std(1)

scaler = StandardScaler()
df[['Age','Fare']] = scaler.fit_transform(df[['Age','Fare']])

# Detect Outliers using boxplot

# Visualize outliers
sns.boxplot(x=df['Fare'])
plt.show()

# Remove extreme outliers in Fare
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1
df = df[(df['Fare'] >= (Q1 - 1.5*IQR)) & (df['Fare'] <= (Q3 + 1.5*IQR))]

# Final Cleaned Data

print(df.head())
print(df.isnull().sum()) # Without Null Values